export const treasuryAbi = [
  {
    inputs: [{ name: "_signers", type: "address[]" }, { name: "_requiredApprovals", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  // ─── Events ──────────────────────────────────────────────────────────
  {
    anonymous: false,
    inputs: [{ indexed: true, name: "signer", type: "address" }],
    name: "SignerAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, name: "signer", type: "address" }],
    name: "SignerRemoved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "txId", type: "uint256" },
      { indexed: true, name: "proposer", type: "address" },
      { indexed: false, name: "to", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "token", type: "address" },
      { indexed: false, name: "memo", type: "string" },
    ],
    name: "TransactionProposed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "txId", type: "uint256" },
      { indexed: true, name: "approver", type: "address" },
    ],
    name: "TransactionApproved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "txId", type: "uint256" },
      { indexed: true, name: "rejector", type: "address" },
      { indexed: false, name: "reason", type: "string" },
    ],
    name: "TransactionRejected",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "txId", type: "uint256" },
      { indexed: true, name: "executor", type: "address" },
    ],
    name: "TransactionExecuted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "txId", type: "uint256" },
      { indexed: true, name: "canceller", type: "address" },
    ],
    name: "TransactionCancelled",
    type: "event",
  },
  // ─── Write Functions ─────────────────────────────────────────────────
  {
    inputs: [
      { name: "_to", type: "address" },
      { name: "_amount", type: "uint256" },
      { name: "_token", type: "address" },
      { name: "_memo", type: "string" },
      { name: "_description", type: "string" },
    ],
    name: "propose",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_txId", type: "uint256" }],
    name: "approve",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_txId", type: "uint256" }, { name: "_reason", type: "string" }],
    name: "reject",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_txId", type: "uint256" }],
    name: "execute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_txId", type: "uint256" }],
    name: "cancel",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_signer", type: "address" }],
    name: "addSigner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_signer", type: "address" }],
    name: "removeSigner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_required", type: "uint256" }],
    name: "setRequiredApprovals",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  // ─── Read Functions ──────────────────────────────────────────────────
  {
    inputs: [],
    name: "getTransactionCount",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getSigners",
    outputs: [{ name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getSignerCount",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "requiredApprovals",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "_txId", type: "uint256" }],
    name: "getTransaction",
    outputs: [
      {
        components: [
          { name: "to", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "token", type: "address" },
          { name: "memo", type: "string" },
          { name: "description", type: "string" },
          { name: "proposer", type: "address" },
          { name: "timestamp", type: "uint256" },
          { name: "executed", type: "bool" },
          { name: "cancelled", type: "bool" },
          { name: "approvalCount", type: "uint256" },
          { name: "rejectionCount", type: "uint256" },
        ],
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "", type: "uint256" }, { name: "", type: "address" }],
    name: "hasApproved",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "", type: "uint256" }, { name: "", type: "address" }],
    name: "hasRejected",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "", type: "address" }],
    name: "isSigner",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  { stateMutability: "payable", type: "receive" },
] as const;
