export const treasuryAbi = [
  {
    inputs: [
      { name: "_signers", type: "address[]" },
      { name: "_lowThreshold", type: "uint256" },
      { name: "_mediumThreshold", type: "uint256" },
      { name: "_highThreshold", type: "uint256" },
      { name: "_timelockDuration", type: "uint256" },
      { name: "_dailyLimit", type: "uint256" },
      { name: "_txExpirationPeriod", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  // ─── Events ──────────────────────────────────────────────────────────
  {
    anonymous: false,
    inputs: [{ indexed: true, name: "signer", type: "address" }],
    name: "SignerAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, name: "signer", type: "address" }],
    name: "SignerRemoved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "txId", type: "uint256" },
      { indexed: true, name: "proposer", type: "address" },
      { indexed: false, name: "to", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "token", type: "address" },
      { indexed: false, name: "memo", type: "string" },
    ],
    name: "TransactionProposed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "txId", type: "uint256" },
      { indexed: true, name: "approver", type: "address" },
    ],
    name: "TransactionApproved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "txId", type: "uint256" },
      { indexed: true, name: "rejector", type: "address" },
      { indexed: false, name: "reason", type: "string" },
    ],
    name: "TransactionRejected",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "txId", type: "uint256" },
      { indexed: true, name: "executor", type: "address" },
    ],
    name: "TransactionExecuted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "txId", type: "uint256" },
      { indexed: true, name: "canceller", type: "address" },
    ],
    name: "TransactionCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "txId", type: "uint256" },
      { indexed: true, name: "signer", type: "address" },
    ],
    name: "ApprovalRevoked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "txId", type: "uint256" },
      { indexed: false, name: "executeAfter", type: "uint256" },
    ],
    name: "TimelockStarted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, name: "by", type: "address" }],
    name: "ContractPaused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, name: "by", type: "address" }],
    name: "ContractUnpaused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "signer", type: "address" },
      { indexed: false, name: "voteCount", type: "uint256" },
      { indexed: false, name: "required", type: "uint256" },
    ],
    name: "UnpauseVoteCast",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: "low", type: "uint256" },
      { indexed: false, name: "medium", type: "uint256" },
      { indexed: false, name: "high", type: "uint256" },
    ],
    name: "ThresholdsUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: "oldLimit", type: "uint256" },
      { indexed: false, name: "newLimit", type: "uint256" },
    ],
    name: "DailyLimitUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: "oldDuration", type: "uint256" },
      { indexed: false, name: "newDuration", type: "uint256" },
    ],
    name: "TimelockDurationUpdated",
    type: "event",
  },
  // OpenZeppelin Pausable events
  {
    anonymous: false,
    inputs: [{ indexed: false, name: "account", type: "address" }],
    name: "Paused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: "account", type: "address" }],
    name: "Unpaused",
    type: "event",
  },
  // ─── Write Functions ─────────────────────────────────────────────────
  {
    inputs: [
      { name: "_to", type: "address" },
      { name: "_amount", type: "uint256" },
      { name: "_token", type: "address" },
      { name: "_memo", type: "string" },
      { name: "_description", type: "string" },
    ],
    name: "propose",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_txId", type: "uint256" }],
    name: "approve",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_txId", type: "uint256" }],
    name: "revokeApproval",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_txId", type: "uint256" }, { name: "_reason", type: "string" }],
    name: "reject",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_txId", type: "uint256" }],
    name: "execute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_txId", type: "uint256" }],
    name: "cancel",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "emergencyPause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "voteUnpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_signer", type: "address" }],
    name: "addSigner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_signer", type: "address" }],
    name: "removeSigner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "_low", type: "uint256" },
      { name: "_medium", type: "uint256" },
      { name: "_high", type: "uint256" },
    ],
    name: "setThresholds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_limit", type: "uint256" }],
    name: "setDailyLimit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_duration", type: "uint256" }],
    name: "setTimelockDuration",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  // ─── Read Functions ──────────────────────────────────────────────────
  {
    inputs: [],
    name: "getTransactionCount",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getSigners",
    outputs: [{ name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getSignerCount",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "_amount", type: "uint256" }],
    name: "getRequiredApprovals",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "_txId", type: "uint256" }],
    name: "getRequiredApprovalsForTx",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "_txId", type: "uint256" }],
    name: "getTransaction",
    outputs: [
      {
        components: [
          { name: "to", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "token", type: "address" },
          { name: "memo", type: "string" },
          { name: "description", type: "string" },
          { name: "proposer", type: "address" },
          { name: "timestamp", type: "uint256" },
          { name: "executed", type: "bool" },
          { name: "cancelled", type: "bool" },
          { name: "approvalCount", type: "uint256" },
          { name: "rejectionCount", type: "uint256" },
          { name: "executeAfter", type: "uint256" },
          { name: "expiresAt", type: "uint256" },
        ],
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "_txId", type: "uint256" }],
    name: "isTransactionExpired",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getDailySpendRemaining",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getThresholds",
    outputs: [
      { name: "low", type: "uint256" },
      { name: "medium", type: "uint256" },
      { name: "high", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "", type: "uint256" }, { name: "", type: "address" }],
    name: "hasApproved",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "", type: "uint256" }, { name: "", type: "address" }],
    name: "hasRejected",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "", type: "address" }],
    name: "isSigner",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "dailyLimit",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "spentToday",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "timelockDuration",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "txExpirationPeriod",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lowThreshold",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "mediumThreshold",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "highThreshold",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "unpauseVoteCount",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  { stateMutability: "payable", type: "receive" },
] as const;
